etl_mvp_project:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: ODBC Driver 18 for SQL Server
      server: "{{ env_var('DBT_HOST') }}"
      port: 1433
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: raw
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      trust_cert: true