version: 2

models:
  - name: stg_region
    description: "Tabla de staging para regiones únicas derivadas del campo 'region' en dbt_data"
    columns:
      - name: id_region
        description: "Clave técnica generada para la región"
      - name: nombre_region
        description: "Nombre de la región geográfica"

  - name: stg_pais
    description: "Tabla de staging para países únicos, relacionados con su región"
    columns:
      - name: id_pais
        description: "Clave técnica del país"
      - name: nombre_pais
        description: "Nombre del país"
      - name: id_region
        description: "Clave técnica de la región a la que pertenece el país"

  - name: stg_metodo_envio
    description: "Tabla de staging para métodos de envío únicos"
    columns:
      - name: id_metodo
        description: "Clave técnica del método de envío"
      - name: nombre_metodo
        description: "Descripción del método de envío (por ejemplo: 'SHIP')"

  - name: stg_producto
    description: "Tabla de staging para tipos de producto y sus precios/costos unitarios"
    columns:
      - name: id_producto
        description: "Clave técnica del producto"
      - name: tipo_producto
        description: "Tipo de producto (fruta, bebida, etc.)"
      - name: precio_unitario
        description: "Precio unitario de venta del producto"
      - name: costo_unitario
        description: "Costo unitario del producto"

  - name: stg_pedido
    description: "Tabla de staging para pedidos únicos, derivados de order_id"
    columns:
      - name: id_pedido
        description: "Identificador de la orden"
      - name: id_pais
        description: "Clave técnica del país asociado al pedido"
      - name: prioridad_pedido
        description: "Prioridad asignada a la orden (por ejemplo: M, H, L)"
      - name: fecha_pedido
        description: "Fecha de creación de la orden"
      - name: fecha_envio
        description: "Fecha estimada o real de envío"
      - name: id_metodo
        description: "Clave técnica del método de envío utilizado"

  - name: stg_detalle_pedido
    description: "Tabla de staging a nivel de línea de detalle de cada pedido"
    columns:
      - name: id_detalle
        description: "Clave técnica del detalle del pedido (order_id + item_type)"
      - name: id_pedido
        description: "Clave del pedido relacionado"
      - name: id_producto
        description: "Clave del producto vendido"
      - name: unidades_vendidas
        description: "Cantidad de unidades vendidas"
      - name: costo_produccion
        description: "Costo de producción total de esas unidades"
      - name: costo_envio
        description: "Costo de envío asociado al detalle"
      - name: costo_aduanas
        description: "Costo de aduanas asociado"
      - name: costo_marketing
        description: "Gastos de marketing atribuidos al detalle"
      - name: costo_almacenamiento
        description: "Costo de almacenamiento de esas unidades"
      - name: otros_costos
        description: "Otros costos indirectos asociados"
      - name: costo_total
        description: "Suma total de todos los costos"
      - name: ingreso_total
        description: "Ingresos totales obtenidos por este detalle"
      - name: ganancia_total
        description: "Ganancia neta: ingresos menos costos"