name: DBT Debug on Push

on:
  push:
    branches:
      - master

jobs:
  dbt-debug:
    runs-on: ubuntu-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Microsoft ODBC Driver 18 for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install dbt
        run: pip install dbt-sqlserver

      - name: Set up DBT profile
        run: |
          mkdir ~/.dbt
          cp .github/profiles.yml ~/.dbt/profiles.yml

      - name: Run dbt debug
        run: dbt debug

      - name: Run DBT
        run: |
          dbt deps
          dbt run
#          dbt test --select dbt_data
#          dbt docs generate
